# Generated by Django 6.0.2 on 2026-02-26 06:23

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.contrib.postgres.operations import BtreeGistExtension
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddField(
            model_name='appointment',
            name='time_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('doctor_clinic', '='), ('time_range', '&&')], name='prevent_overlapping_appointments'),
        ),
    ]
