# Generated by Django 6.0.2 on 2026-05-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_latitude_clinic_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='subscription_status',
            field=models.CharField(blank=True, help_text='e.g. active, past_due, canceled', max_length=50, null=True),
        ),
    ]
