# Generated by Django 6.0.2 on 2026-05-07 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0003_clinic_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='STARTER', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIALING', 'Trialing'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clinics.clinic')),
            ],
        ),
    ]
